include:
  - project: "signageos/infra/gitlab-ci"
    file: "/pipelines/ts-lib-public.yaml"
    ref: master
    inputs:
      disable-prettier: true
      disable-checktypes: true

.upstream:documentation:
  stage: release
  when: on_success
  needs:
    - build:build-npm-package
  trigger:
    project: signageos/services/documentation
    strategy: depend
    branch: master

upstream:check:documentation:
  extends:
    - .upstream:documentation
  except:
    - tags
  variables:
    SMIL_PLAYER_PRERELEASE_TAG: $CI_COMMIT_REF_SLUG

upstream:deploy:documentation:
  extends:
    - .upstream:documentation
  only:
    - tags
  variables:
    FORCE_DEPLOY: production
