version: '3'
services:
    app:
        build:
            context: .
            dockerfile: Dockerfile
            cache_from: ['172396373649.dkr.ecr.eu-central-1.amazonaws.com/signageos/smil-player/runtime:latest']
            target: dev
            tags: ['172396373649.dkr.ecr.eu-central-1.amazonaws.com/signageos/smil-player/runtime:latest']
        volumes:
            - .:/app
        working_dir: /app
        env_file:
            - ~/.signageos/npm.env
        environment:
            TZ: 'Europe/Prague'
        command: tail -f /dev/null
